services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/kpi_db
      - SELENIUM_URL=http://selenium:4444/wd/hub
    depends_on:
      - mongodb
      - selenium

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900" # VNC port để xem live (nếu cần)

volumes:
  mongodb_data:
