/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamsIndexRouteImport } from './routes/exams.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherExamsRouteImport } from './routes/teacher.exams'
import { Route as ExamsIdRouteImport } from './routes/exams.$id'
import { Route as AttemptsIdRouteImport } from './routes/attempts.$id'
import { Route as AttemptExamIdRouteImport } from './routes/attempt.$examId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminKpiIndexRouteImport } from './routes/admin/kpi.index'
import { Route as AdminExamsIndexRouteImport } from './routes/admin/exams.index'
import { Route as AdminKpiStatsRouteImport } from './routes/admin/kpi.stats'
import { Route as AdminKpiReconciliationRouteImport } from './routes/admin/kpi.reconciliation'
import { Route as AdminKpiJobIdRouteImport } from './routes/admin/kpi.$jobId'
import { Route as AdminExamsNewRouteImport } from './routes/admin/exams.new'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExamsRoute = TeacherExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => TeacherRoute,
} as any)
const ExamsIdRoute = ExamsIdRouteImport.update({
  id: '/exams/$id',
  path: '/exams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptsIdRoute = AttemptsIdRouteImport.update({
  id: '/attempts/$id',
  path: '/attempts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptExamIdRoute = AttemptExamIdRouteImport.update({
  id: '/attempt/$examId',
  path: '/attempt/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKpiIndexRoute = AdminKpiIndexRouteImport.update({
  id: '/admin/kpi/',
  path: '/admin/kpi/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsIndexRoute = AdminExamsIndexRouteImport.update({
  id: '/admin/exams/',
  path: '/admin/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKpiStatsRoute = AdminKpiStatsRouteImport.update({
  id: '/admin/kpi/stats',
  path: '/admin/kpi/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKpiReconciliationRoute = AdminKpiReconciliationRouteImport.update({
  id: '/admin/kpi/reconciliation',
  path: '/admin/kpi/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKpiJobIdRoute = AdminKpiJobIdRouteImport.update({
  id: '/admin/kpi/$jobId',
  path: '/admin/kpi/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsNewRoute = AdminExamsNewRouteImport.update({
  id: '/admin/exams/new',
  path: '/admin/exams/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/attempt/$examId': typeof AttemptExamIdRoute
  '/attempts/$id': typeof AttemptsIdRoute
  '/exams/$id': typeof ExamsIdRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/kpi/$jobId': typeof AdminKpiJobIdRoute
  '/admin/kpi/reconciliation': typeof AdminKpiReconciliationRoute
  '/admin/kpi/stats': typeof AdminKpiStatsRoute
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/admin/kpi/': typeof AdminKpiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/attempt/$examId': typeof AttemptExamIdRoute
  '/attempts/$id': typeof AttemptsIdRoute
  '/exams/$id': typeof ExamsIdRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/exams': typeof ExamsIndexRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/kpi/$jobId': typeof AdminKpiJobIdRoute
  '/admin/kpi/reconciliation': typeof AdminKpiReconciliationRoute
  '/admin/kpi/stats': typeof AdminKpiStatsRoute
  '/admin/exams': typeof AdminExamsIndexRoute
  '/admin/kpi': typeof AdminKpiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/attempt/$examId': typeof AttemptExamIdRoute
  '/attempts/$id': typeof AttemptsIdRoute
  '/exams/$id': typeof ExamsIdRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/admin/exams/new': typeof AdminExamsNewRoute
  '/admin/kpi/$jobId': typeof AdminKpiJobIdRoute
  '/admin/kpi/reconciliation': typeof AdminKpiReconciliationRoute
  '/admin/kpi/stats': typeof AdminKpiStatsRoute
  '/admin/exams/': typeof AdminExamsIndexRoute
  '/admin/kpi/': typeof AdminKpiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/student'
    | '/teacher'
    | '/admin/users'
    | '/attempt/$examId'
    | '/attempts/$id'
    | '/exams/$id'
    | '/teacher/exams'
    | '/teacher/students'
    | '/admin/'
    | '/exams/'
    | '/admin/exams/new'
    | '/admin/kpi/$jobId'
    | '/admin/kpi/reconciliation'
    | '/admin/kpi/stats'
    | '/admin/exams/'
    | '/admin/kpi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/student'
    | '/teacher'
    | '/admin/users'
    | '/attempt/$examId'
    | '/attempts/$id'
    | '/exams/$id'
    | '/teacher/exams'
    | '/teacher/students'
    | '/admin'
    | '/exams'
    | '/admin/exams/new'
    | '/admin/kpi/$jobId'
    | '/admin/kpi/reconciliation'
    | '/admin/kpi/stats'
    | '/admin/exams'
    | '/admin/kpi'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/signup'
    | '/student'
    | '/teacher'
    | '/admin/users'
    | '/attempt/$examId'
    | '/attempts/$id'
    | '/exams/$id'
    | '/teacher/exams'
    | '/teacher/students'
    | '/admin/'
    | '/exams/'
    | '/admin/exams/new'
    | '/admin/kpi/$jobId'
    | '/admin/kpi/reconciliation'
    | '/admin/kpi/stats'
    | '/admin/exams/'
    | '/admin/kpi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRoute
  TeacherRoute: typeof TeacherRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AttemptExamIdRoute: typeof AttemptExamIdRoute
  AttemptsIdRoute: typeof AttemptsIdRoute
  ExamsIdRoute: typeof ExamsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  AdminExamsNewRoute: typeof AdminExamsNewRoute
  AdminKpiJobIdRoute: typeof AdminKpiJobIdRoute
  AdminKpiReconciliationRoute: typeof AdminKpiReconciliationRoute
  AdminKpiStatsRoute: typeof AdminKpiStatsRoute
  AdminExamsIndexRoute: typeof AdminExamsIndexRoute
  AdminKpiIndexRoute: typeof AdminKpiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/exams': {
      id: '/teacher/exams'
      path: '/exams'
      fullPath: '/teacher/exams'
      preLoaderRoute: typeof TeacherExamsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/exams/$id': {
      id: '/exams/$id'
      path: '/exams/$id'
      fullPath: '/exams/$id'
      preLoaderRoute: typeof ExamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempts/$id': {
      id: '/attempts/$id'
      path: '/attempts/$id'
      fullPath: '/attempts/$id'
      preLoaderRoute: typeof AttemptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempt/$examId': {
      id: '/attempt/$examId'
      path: '/attempt/$examId'
      fullPath: '/attempt/$examId'
      preLoaderRoute: typeof AttemptExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kpi/': {
      id: '/admin/kpi/'
      path: '/admin/kpi'
      fullPath: '/admin/kpi/'
      preLoaderRoute: typeof AdminKpiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams/': {
      id: '/admin/exams/'
      path: '/admin/exams'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AdminExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kpi/stats': {
      id: '/admin/kpi/stats'
      path: '/admin/kpi/stats'
      fullPath: '/admin/kpi/stats'
      preLoaderRoute: typeof AdminKpiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kpi/reconciliation': {
      id: '/admin/kpi/reconciliation'
      path: '/admin/kpi/reconciliation'
      fullPath: '/admin/kpi/reconciliation'
      preLoaderRoute: typeof AdminKpiReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kpi/$jobId': {
      id: '/admin/kpi/$jobId'
      path: '/admin/kpi/$jobId'
      fullPath: '/admin/kpi/$jobId'
      preLoaderRoute: typeof AdminKpiJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams/new': {
      id: '/admin/exams/new'
      path: '/admin/exams/new'
      fullPath: '/admin/exams/new'
      preLoaderRoute: typeof AdminExamsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeacherRouteChildren {
  TeacherExamsRoute: typeof TeacherExamsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherExamsRoute: TeacherExamsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRoute,
  TeacherRoute: TeacherRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AttemptExamIdRoute: AttemptExamIdRoute,
  AttemptsIdRoute: AttemptsIdRoute,
  ExamsIdRoute: ExamsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  AdminExamsNewRoute: AdminExamsNewRoute,
  AdminKpiJobIdRoute: AdminKpiJobIdRoute,
  AdminKpiReconciliationRoute: AdminKpiReconciliationRoute,
  AdminKpiStatsRoute: AdminKpiStatsRoute,
  AdminExamsIndexRoute: AdminExamsIndexRoute,
  AdminKpiIndexRoute: AdminKpiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
